# ！由于 GitHub 到 TKE 间网络环境不佳
# ！暂停使用本工作流

# GitHub 工作流
# 部署到生产环境（TKE, Tencent Kubernetes Engine）
#
# 需配置以下密钥
#  - TENCENT_CLOUD_ACCOUNT_ID: 腾讯云账户 ID
#  - TKE_REGISTRY_SERVER: TKE 镜像仓库地址（包含路径）
#  - TKE_REGISTRY_PASSWORD: TKE 镜像仓库密码

# 工作流名称
name: Deploy to production(TKE)

# 触发工作流方式，workflow_dispatch 表示手动触发
on: workflow_dispatch

# 作业清单
jobs:
  # 作业唯一标识符
  deploy-to-production-tke:
    # 作业名称
    name: 部署到生产环境（TKE）
    # 运行作业的机器类型
    runs-on: ubuntu-latest
    # 作业引用的环境
    environment: production
    # 作业包含的一系列步骤（任务）
    steps:
      # 步骤1
      - name: 检出代码
        uses: actions/checkout@v3

      # 步骤2
      - name: 构建 Docker 镜像
        run: |
          docker build -t ${{ secrets.TKE_REGISTRY_SERVER }}:${GITHUB_SHA} .

      # 步骤3
      - name: 登录 TKE 镜像仓库
        run: |
          docker login -u ${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }} -p '${{ secrets.TKE_REGISTRY_PASSWORD }}' ${{ secrets.TKE_REGISTRY_SERVER }}

      # 步骤4
      - name: 将 Docker 镜像推到 TKE 镜像仓库
        run: |
          docker push ${{ secrets.TKE_REGISTRY_SERVER }}:${GITHUB_SHA}

      ########## 以下未验证 ##########
      - name: Set up Kustomize
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Set up ~/.kube/config for connecting TKE cluster
        uses: TencentCloud/tke-cluster-credential-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          tke_region: ${{ secrets.TKE_REGION }}
          cluster_id: ${{ secrets.TKE_CLUSTER_ID }}
      - name: Switch to TKE context
        run: |
          kubectl config use-context ${TKE_CLUSTER_ID}-context-default
      - name: Deploy
        run: |
          ./kustomize edit set image ${TKE_REGISTRY_SERVER}:${GITHUB_SHA}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
          kubectl get services -o wide
