# GitHub 工作流
# 部署到生产环境（TKE, Tencent Kubernetes Engine）

# 工作流名称
name: Deploy to production(TKE)

# 触发工作流方式，workflow_dispatch 表示手动触发
on: workflow_dispatch

# 作业清单
jobs:
  # 作业唯一标识符
  deploy-to-production-tke:
    # 作业名称
    name: 部署到生产环境（TKE）
    # 运行作业的机器类型
    runs-on: ubuntu-latest
    # 作业引用的环境
    environment: production
    # 作业包含的一系列步骤（任务）
    steps:
      # 步骤1
      - name: 检出代码
        uses: actions/checkout@v3

      # 步骤2
      - name: 构建 Docker 镜像
        run: |
          docker build -t ${{ secrets.TKE_REGISTRY_SERVER }}:${GITHUB_SHA} .

      # 步骤3
      - name: 登录 TKE 镜像仓库
        run: |
          docker login -u ${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }} -p '${{ secrets.TKE_REGISTRY_PASSWORD }}' ${{ secrets.TKE_REGISTRY_SERVER }}

      # 步骤4
      - name: 将 Docker 镜像推到 TKE 镜像仓库
        run: |
          docker push ${{ secrets.TKE_REGISTRY_SERVER }}:${GITHUB_SHA}
